//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Manage
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayIn { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPhong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
